services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - edgetts
    volumes:
      - suaraka_storage:/app/.storage

  edgetts:
    build: ./edgetts-server
    ports:
      - "8100:8100"

volumes:
  suaraka_db:
  suaraka_storage:
